### ISSUE TITLE
試用電子看板鼎捷2個月

### ISSUE THREAD

**Issue by twoutlook** [ft2017/ft-advanced#4]
http://ftks18.com/10/d3   
## (2)注明一下, 鼎捷的範例, 或是我們自主開發

**Comment by ft2017** [comment]
已完成
![default](https://user-images.githubusercontent.com/25809263/37189127-ab00c544-238d-11e8-8453-a552bae543a8.png)

**Comment by twoutlook** [comment]
## "注明一下, 鼎捷的範例, 或是我們自主開發", 尚未實現
