### ISSUE TITLE
試用電子看板鼎捷2個月 第2點請實施

### ISSUE THREAD

**Issue by twoutlook** [ft2017/ft-advanced#6]
http://ftks18.com/10/d3

(1)試用2個月 ,加括號注明起止日期。--- OK
(2)注明一下, 鼎捷的範例, 或是我們自主開發 --- 請實施

**Comment by ft2017** [comment]
已注明
![default](https://user-images.githubusercontent.com/25809263/37191773-ab9ea278-239c-11e8-8cc5-91b68baabc4e.png)
