### ISSUE TITLE
換頁時間改為60秒, 其它範例都改為60秒(就算單頁)

### ISSUE THREAD

**Issue by ft2017** [ft2017/ft-advanced#7]
Mark，2018-03-09提出，试用鼎捷电子看板程序中，自主开发报表。換頁時間改為60秒, 其它範例都改為60秒(就算單頁)

**Comment by twoutlook** [comment]
![2018-03-003](https://user-images.githubusercontent.com/16488072/37191995-cbda5aea-239d-11e8-8f03-88c82c684920.PNG)
