### ISSUE TITLE
工单的RUNCARD数量统计表(只限已結案的)要加成本結案的

### ISSUE THREAD

**Issue by twoutlook** [ft2017/ft-advanced#8]
http://10.10.0.100/cust001/case/a25.php?app=case&page=a21_wo_rcard_ok
![2018-03-004](https://user-images.githubusercontent.com/16488072/37192129-ae54e110-239e-11e8-818e-a6aa6007eeed.PNG)
工单的RUNCARD数量统计表(只限已結案的) =>工单的RUNCARD数量统计表(只限已結案和成本結案的)

**Comment by ft2017** [comment]
已完成
![default](https://user-images.githubusercontent.com/25809263/37196149-ab166fb6-23b0-11e8-950d-2ee2a931ae63.png)
